Converted workflows to Orquesta
StackStorm-Exchange/stackstorm-hpe_icsp pull request #9
Opened 2020-09-25 12:57 UTC by nmaludy

Closes #8

2020-09-25 15:37 UTC, amanda11 requested changes
Can you update the version in pack.yaml, I didn't see it as part of the PR?

2020-09-25 16:00 UTC, amanda11 requested changes
I had a few comments due to the single/multi split. Mainly on wording but a few cases I'm not sure if arrays are needed that are missing.

2020-09-25 16:00 UTC, amanda11 commented on README.md
> +* `hpe_icsp.icsp_multi_server_attribute_add` - Apply Attribute with server unique values for a single server.
I think the new line should be icsp_single_server_attribute_add - as have duplicate multi_server_attribute_add in the README.

2020-09-25 16:00 UTC, amanda11 commented on actions/workflows/icsp_id_to_os.yaml
> +description: Deploy an OS to a list of Servers
Can we change description as this is to single server not list of servers?

2020-09-25 16:00 UTC, amanda11 commented on actions/icsp_single_server_attribute_add.yaml
> +    description: List of Values to be set against servers. Must match order of identifier.
Suggest changing it to be "against the server" rather than "against servers" - as this is for single server. And not sure the "Must match order of identifier makes sense".
Also now that this is a single server, is it still an array, is it not a single value now?

2020-09-25 16:00 UTC, amanda11 commented on actions/workflows/icsp_single_server_attribute_add.yaml
> +        - <% ctx().identifier %>
In the original action-chain then what was passed was an array with a single element in e.g. [<% $.identifier %>], now it's a single string. Is the [] still required to make sure an array is passed?

2020-09-25 16:00 UTC, amanda11 commented on actions/workflows/icsp_id_to_os.yaml
> +      - when: <% succeeded() and (ctx().id_type = 'UUID') %>
Is the succeeded() needed on these when's? Could just have the when on the ctx().id_type value.

2020-09-25 16:00 UTC, amanda11 commented on actions/workflows/icsp_id_to_os.yaml
> +        - <% ctx().identifier %>
Does the <% ctx().identifier %> need a [] added around it, like in the original action-chain, as icsp_mid_get expects an array, so before we were sending an array of 1 item?

2020-09-25 16:00 UTC, amanda11 commented on actions/workflows/icsp_id_to_os.yaml
> +        - <% ctx().icsp_mid %>
Does the <% ctx().identifier %> need a [] added around it, like in the original action-chain, as icsp_mid_get expects an array, so before we were sending an array of 1 item?

2020-09-25 16:00 UTC, amanda11 commented on actions/workflows/icsp_id_to_os.yaml
> +        - <% ctx().hostname %>
Does the <% ctx().hostname %> need a [] added around it, like in the original action-chain, as icsp_mid_get expects an array, so before we were sending an array of 1 item?

2020-09-25 16:00 UTC, amanda11 commented on actions/workflows/icsp_id_to_os.yaml
> +        - <% ctx().identifier %>
Does the <% ctx().identifier %> need a [] added around it, like in the original action-chain, as icsp_mid_get expects an array, so before we were sending an array of 1 item?

2020-09-25 16:03 UTC, amanda11 requested changes

2020-09-25 16:03 UTC, amanda11 commented on actions/icsp_id_to_os.yaml
> +    type: array
Isn't this now a single string being passed not an array. And therefore also the description doesn't need the comment about "Must match order of identifiers"

2020-09-25 17:37 UTC, blag commented on actions/workflows/icsp_id_to_os.yaml
> +        - <% ctx().identifier %>
Nope, the `[]` is JSON syntax (which can be embedded in the middle of YAML, as it was originally), but in this pure YAML syntax, arrays are specified on an optionally indented new line with `-` in front:

```yaml
array name:
  - element 1
  - element 2
  - element 3
```

So `identifiers` is specified as an array with a single element: whatever is in `ctx().identifier`.

I believe this is also the case in your other comments regarding this.

2020-09-25 17:38 UTC, blag commented on actions/workflows/icsp_id_to_os.yaml
> +        - <% ctx().identifier %>
See [my comment](https://github.com/StackStorm-Exchange/stackstorm-hpe_icsp/pull/9/files#r495136823).

2020-09-25 17:38 UTC, blag commented on actions/workflows/icsp_id_to_os.yaml
> +        - <% ctx().icsp_mid %>
See [my comment](https://github.com/StackStorm-Exchange/stackstorm-hpe_icsp/pull/9/files#r495136823).

2020-09-25 17:38 UTC, blag commented on actions/workflows/icsp_id_to_os.yaml
> +        - <% ctx().hostname %>
See [my comment](https://github.com/StackStorm-Exchange/stackstorm-hpe_icsp/pull/9/files#r495136823).

2020-09-25 18:47 UTC, amanda11 commented on actions/workflows/icsp_id_to_os.yaml
> +        - <% ctx().identifier %>
@blag Good point I hadn't appreciated the - on those lines - all good - I'll mark t hose comments as resolved.

2020-09-25 19:01 UTC, amanda11 commented
> I had a few comments due to the single/multi split. Mainly on wording but a few cases I'm not sure if arrays are needed that are missing.

Thanks to @blag, I realised I hadn't appreciated the JSON formatting on the arrays. So just some minor comments on wording I think is left. Have resolved the comments that have been confirmed as not needed.

2020-11-03 05:51 UTC, blag commented on actions/workflows/icsp_id_to_os.yaml
> +      - when: <% succeeded() and (ctx().id_type = 'UUID') %>
It's not required, but it doesn't hurt anything.

2020-11-03 05:53 UTC, blag commented
Resolved the issues @amanda11 raised. The last two commits could be re-reviewed.

2020-11-03 10:26 UTC, blag approved these changes

2020-11-03 11:05 UTC, amanda11 commented
LGTM, but think the pack.yaml needs an update to increment the version string?

2020-11-03 12:53 UTC, nmaludy commented
@amanda11 correct, the pack version increment needs to be the final commit in a PR, otherwise the deployment code will tag the wrong commit (whatever commit changes the pack.yaml).

2020-11-03 13:10 UTC, merged